version: "3.0"

services:
  api:
    env_file:
      - ./api/.env
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
